### ISSUE TITLE
transferの機能テストで"error TypeError: b must be a Uint8Array"が発生

### ISSUE THREAD

**Issue by yk-saito** [unchain-tech/Solana-Wallet#6]
## テスト方法
1. Solana local nodeをたちあげる

```bash
solana-test-validator
```
2. テストを実行
```bash
npm run test
```

## エラー内容

```bash
# log出力省略

 console.log
    送金中...

      at log (pages/index.js:107:15)

  console.log
    Transfer params: {
      fromPubkey: 'k9yzthw2PfSexhfCUdMXFqkNenBBvhYApLQHUQ5SLuY',
      toPubkey: 'k9yzthw2PfSexhfCUdMXFqkNenBBvhYApLQHUQ5SLuY',
      lamports: 1000000000
    }

      at log (pages/index.js:112:15)

  console.log
    error TypeError: b must be a Uint8Array
        at checkUint8Array (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/@solana/buffer-layout/src/Layout.ts:149:11)
        at uint8ArrayToBuffer (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/@solana/buffer-layout/src/Layout.ts:157:3)
        at UInt.encode (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/@solana/buffer-layout/src/Layout.ts:588:5)
        at Structure.encode (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/@solana/buffer-layout/src/Layout.ts:1205:26)
        at encode (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/@solana/web3.js/src/instruction.ts:32:15)
        at Function.encodeData [as transfer] (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/@solana/web3.js/src/system-program.ts:759:14)
        at transfer (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/pages/index.js:118:42)
        at HTMLUnknownElement.callCallback (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/react-dom/cjs/react-dom.development.js:4157:14)
        at HTMLUnknownElement.callTheUserObjectsOperation (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
        at innerInvokeEventListeners (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:350:25)
        at invokeEventListeners (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
        at HTMLUnknownElementImpl._dispatch (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
        at HTMLUnknownElement.dispatchEvent (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
        at Object.invokeGuardedCallbackDev (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/react-dom/cjs/react-dom.development.js:4206:16)
        at invokeGuardedCallback (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/react-dom/cjs/react-dom.development.js:4270:31)
        at invokeGuardedCallbackAndCatchFirstError (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/react-dom/cjs/react-dom.development.js:4284:25)
        at executeDispatch (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/react-dom/cjs/react-dom.development.js:9011:3)
        at processDispatchQueueItemsInOrder (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/react-dom/cjs/react-dom.development.js:9043:7)
        at processDispatchQueue (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/react-dom/cjs/react-dom.development.js:9056:5)
        at dispatchEventsForPlugins (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/react-dom/cjs/react-dom.development.js:9067:3)
        at /Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/react-dom/cjs/react-dom.development.js:9258:12
        at batchedUpdates$1 (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/react-dom/cjs/react-dom.development.js:25979:12)
        at batchedUpdates (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/react-dom/cjs/react-dom.development.js:3984:12)
        at dispatchEventForPluginEventSystem (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/react-dom/cjs/react-dom.development.js:9257:3)
        at dispatchEvent (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/react-dom/cjs/react-dom.development.js:6435:5)
        at dispatchDiscreteEvent (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/react-dom/cjs/react-dom.development.js:6410:5)
        at HTMLDivElement.callTheUserObjectsOperation (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
        at innerInvokeEventListeners (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:350:25)
        at invokeEventListeners (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
        at HTMLFormElementImpl._dispatch (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
        at fireAnEvent (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
        at HTMLFormElementImpl.requestSubmit (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/jsdom/lib/jsdom/living/nodes/HTMLFormElement-impl.js:109:10)
        at HTMLFormElementImpl._doRequestSubmit (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/jsdom/lib/jsdom/living/nodes/HTMLFormElement-impl.js:79:10)
        at HTMLInputElementImpl._activationBehavior (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/jsdom/lib/jsdom/living/nodes/HTMLInputElement-impl.js:204:12)
        at HTMLInputElementImpl._dispatch (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:252:26)
        at HTMLInputElementImpl.dispatchEvent (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
        at HTMLInputElement.dispatchEvent (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
        at /Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/@testing-library/user-event/dist/cjs/event/dispatchEvent.js:47:43
        at /Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/@testing-library/react/dist/pure.js:93:16
        at /Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/@testing-library/react/dist/act-compat.js:47:24
        at act (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/react/cjs/react.development.js:2507:16)
        at /Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/@testing-library/react/dist/act-compat.js:46:25
        at Object.eventWrapper (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/@testing-library/react/dist/pure.js:92:28)
        at Object.wrapEvent (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/@testing-library/user-event/dist/cjs/event/wrapEvent.js:8:28)
        at Object.dispatchEvent (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/@testing-library/user-event/dist/cjs/event/dispatchEvent.js:47:22)
        at Object.dispatchUIEvent (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/@testing-library/user-event/dist/cjs/event/dispatchEvent.js:24:26)
        at Mouse.up (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/@testing-library/user-event/dist/cjs/system/pointer/mouse.js:91:30)
        at PointerHost.release (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/@testing-library/user-event/dist/cjs/system/pointer/index.js:74:28)
        at pointerAction (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/@testing-library/user-event/dist/cjs/pointer/index.js:62:47)
        at Object.pointer (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/@testing-library/user-event/dist/cjs/pointer/index.js:35:9)
        at Object.asyncWrapper (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/node_modules/@testing-library/react/dist/pure.js:73:22)
        at Object.<anonymous> (/Users/yukasaito/Desktop/git/unchain/solana/Solana-Wallet/__tests__/index.test.js:174:7)

      at log (pages/index.js:146:15)

 FAIL  __tests__/index.test.js (5.192 s)
  Home
    ✓ generates wallet (159 ms)
    ✓ import wallet (248 ms)
    Import and use Alice's Wallet
      ✓ get balance (561 ms)
      ✓ airdrop (1825 ms)
      ✕ transfer (1988 ms)

  ● Home › Import and use Alice's Wallet › transfer

    expect(received).toBeInTheDocument()

    received value must be an HTMLElement or an SVGElement.
    Received has value: null

    Ignored nodes: comments, script, style
    <html>
      <head />
      <body>
        <div />
        <div>
          <div>
            <div
              class="p-10"
            >
              <h1
                class="text-5xl font-extrabold tracking-tight text-gray-900"
              >
                <span
                  class="text-[#9945FF]"
                >
                  Solana
                </span>
                ウォレットを作ろう！
              </h1>
              <div
                class="mx-auto mt-5 text-gray-500"
              >
                Solanaウォレットの新規作成、インポート、エアドロップ、送金機能の開発にチャレンジしてみよう
              </div>
              <hr
                class="my-6"
              />
              <div>
                <h3
                  class="p-2 border-dotted border-l-8 border-l-indigo-600"
                >
                  My Wallet
                </h3>
                <div
                  class="my-6 text-indigo-600 font-bold"
                >
                  <span>
                    アドレス: 
                  </span>
                  <span
                    data-testid="address"
                  >
                    k9yzthw2PfSexhfCUdMXFqkNenBBvhYApLQHUQ5SLuY
                  </span>
                </div>
                <div
                  class="my-6 font-bold"
                >
                  ネットワーク: 
                  https://api.devnet.solana.com
                </div>
                <div
                  class="my-6 font-bold"
                  data-testid="balance"
                >
                  💰 残高: 
                  2
                   SOL
                </div>
              </div>
              <hr
                class="my-6"
              />
              <div>
                <h2
                  class="p-2 border-dotted border-l-4 border-l-indigo-400"
                >
                  STEP1: ウォレットを新規作成する
                </h2>
                <button
                  class="p-2 my-6 text-white bg-indigo-500 focus:ring focus:ring-indigo-300 rounded-lg cursor-pointer"
                >
                  ウォレットを生成
                </button>
                <div
                  class="mt-1 p-4 border border-gray-300 bg-gray-200"
                  data-testid="mnemonic-display"
                >
                  enjoy coach pull ready spice hair burden surge life place exotic kingdom
                </div>
                <strong
                  class="text-xs"
                >
                  このフレーズは秘密にして、安全に保管してください。このフレーズが漏洩すると、誰でもあなたの資産にアクセスできてしまいます。
                  <br />
                  オンライン銀行口座のパスワードのようなものだと考えてください。
                </strong>
              </div>
              <hr
                class="my-6"
              />
              <div>
                <h2
                  class="p-2 border-dotted border-l-4 border-l-indigo-400"
                >
                  STEP2: 既存のウォレットをインポートする
                </h2>
                <form
                  class="my-6"
                >
                  <div
                    class="flex items-center border-b border-indigo-500 py-2"
                  >
                    <input
                      class="w-full text-gray-700 mr-3 p-1 focus:outline-none"
                      placeholder="シークレットリカバリーフレーズ"
                      type="text"
                    />
                    <input
                      class="p-2 text-white bg-indigo-500 focus:ring focus:ring-indigo-300 rounded-lg cursor-pointer"
                      type="submit"
                      value="インポート"
                    />
                  </div>
                </form>
              </div>
              <hr
                class="my-6"
              />
              <div>
                <h2
                  class="p-2 border-dotted border-l-4 border-l-indigo-400"
                >
                  STEP3: 残高を取得する
                </h2>
                <button
                  class="p-2 my-6 text-white bg-indigo-500 focus:ring focus:ring-indigo-300 rounded-lg cursor-pointer"
                >
                  残高を取得
                </button>
              </div>
              <hr
                class="my-6"
              />
              <div>
                <h2
                  class="p-2 border-dotted border-l-4 border-l-indigo-400"
                >
                  STEP4: エアドロップ機能を実装する
                </h2>
                <button
                  class="p-2 my-6 text-white bg-indigo-500 focus:ring focus:ring-indigo-300 rounded-lg cursor-pointer"
                >
                  Airdrop
                </button>
              </div>
              <hr
                class="my-6"
              />
              <div>
                <h2
                  class="p-2 border-dotted border-l-4 border-l-indigo-400"
                >
                  STEP5: 送金機能を実装する
                </h2>
                <form
                  class="my-6"
                >
                  <div
                    class="flex items-center border-b border-indigo-500 py-2"
                  >
                    <input
                      class="w-full text-gray-700 mr-3 p-1 focus:outline-none"
                      placeholder="送金先のウォレットアドレス"
                      type="text"
                    />
                    <input
                      class="p-2 text-white bg-indigo-500 focus:ring focus:ring-indigo-300 rounded-lg cursor-pointer"
                      type="submit"
                      value="送金"
                    />
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>

      176 |       /** ローディングインジケータが表示されるまで待機する */
      177 |       await waitFor(() => {
    > 178 |         expect(screen.queryByTestId('loading-transfer')).toBeInTheDocument();
          |                                                          ^
      179 |       });
      180 |       /** 非同期処理が終わるまで待機する */
      181 |       await waitForElementToBeRemoved(

      at __EXTERNAL_MATCHER_TRAP__ (node_modules/expect/build/index.js:317:30)
      at Object.throwingMatcher [as toBeInTheDocument] (node_modules/expect/build/index.js:318:15)
      at toBeInTheDocument (__tests__/index.test.js:178:58)
      at runWithExpensiveErrorDiagnosticsDisabled (node_modules/@testing-library/dom/dist/config.js:47:12)
      at checkCallback (node_modules/@testing-library/dom/dist/wait-for.js:127:77)
      at checkRealTimersCallback (node_modules/@testing-library/dom/dist/wait-for.js:121:16)
      at Timeout.task [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:520:19)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 4 passed, 5 total
Snapshots:   0 total
Time:        5.409 s, estimated 24 s
Ran all test suites.
```

## その他
以下のログ出力にあるように、送金するアドレスと受け取るアドレスが同じになってしまっている点も解決できていないです。
```
  console.log
    Transfer params: {
      fromPubkey: 'k9yzthw2PfSexhfCUdMXFqkNenBBvhYApLQHUQ5SLuY',
      toPubkey: 'k9yzthw2PfSexhfCUdMXFqkNenBBvhYApLQHUQ5SLuY',
      lamports: 1000000000
    }
```

### アプリケーション全体像

![Screen Shot 2023-04-25 at 14 00 41](https://user-images.githubusercontent.com/60546319/234178952-eb3713fe-044a-47c1-a586-bc5543d60c85.png)

**Comment by yk-saito** [comment]
テスト方法を変更することで対処しました(#4)。
